1.Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.

Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

2. Aşağıda verilen iki boyutlu ve üç boyutlu arrayi oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım.

İki boyutlu array:
[[1,2,6,7],
[4,3,9,5]]

Üç boyutlu array:
[[[7,5,14],[21,8,11]],
[[8,6,20],[14,3,9]]]

3. İstenilen elamanlara ulaşmak için arrayler üzerinde indexleme işlemi yapalım.

İki boyutlu arraydaki 2 elemanına ulaşalım.

İki boyutlu arraydaki 7 elemanına ulaşalım.

Üç boyutlu arraydaki 9 elemanına ulaşalım.

Üç boyutlu arraydaki 5 elemanına ulaşalım.

4. Arrayler üzerinde slicing işlemi uygulayalım.

İki boyutlu arraydaki 2,6 elemanlarına ulaşalım.

İki boyutlu arraydaki 3,9,5 elemanlarına ulaşalım.

Üç boyutlu arraydaki 21,8,11 elemanlarına ulaşalım.

Üç boyutlu arraydaki 6,20 elemanlarına ulaşalım.

5. 5 satır 3 sütunluk sıfırlardan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim.

In [7]:
# 1.Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.
import numpy as np
array = np.array([1,2,3,4,5], dtype = int)
array

array([1, 2, 3, 4, 5])

In [11]:
# Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

print(array.ndim)
print(array.shape)
print(array.size)

1
(5,)
5


In [16]:
# 2. Aşağıda verilen iki boyutlu ve üç boyutlu arrayi oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım.


array2 = np.array([[1,2,6,7],
[4,3,9,5]])


array3 = np.array([[[7,5,14],[21,8,11]],
[[8,6,20],[14,3,9]]])

print(array2)
print(array3)

[[1 2 6 7]
 [4 3 9 5]]
[[[ 7  5 14]
  [21  8 11]]

 [[ 8  6 20]
  [14  3  9]]]


In [17]:
print(array2.ndim) # boyut bilgisi
print(array2.shape) # satır sütun bilgisi
print(array2.size) # eleman sayısı 

2
(2, 4)
8


In [18]:
print(array3.ndim)
print(array3.shape)
print(array3.size)

3
(2, 2, 3)
12


In [19]:
array2

array([[1, 2, 6, 7],
       [4, 3, 9, 5]])

In [20]:
# 3. İstenilen elamanlara ulaşmak için arrayler üzerinde indexleme işlemi yapalım.
# İki boyutlu arraydaki 2 elemanına ulaşalım.
array2[0,1] # [satır, sütun]

2

In [21]:
# İki boyutlu arraydaki 7 elemanına ulaşalım.
array2[0,3]

7

In [22]:
array3

array([[[ 7,  5, 14],
        [21,  8, 11]],

       [[ 8,  6, 20],
        [14,  3,  9]]])

In [23]:
# Üç boyutlu arraydaki 9 elemanına ulaşalım.
array3[1,1,2]

9

In [ ]:
# Üç boyutlu arraydaki 5 elemanına ulaşalım.

In [24]:
array3[0,0,1]

5

In [25]:
array2

array([[1, 2, 6, 7],
       [4, 3, 9, 5]])

In [29]:
# 4. Arrayler üzerinde slicing işlemi uygulayalım.
#İki boyutlu arraydaki 2,6 elemanlarına ulaşalım.
array2[0, 1:3]

array([2, 6])

In [30]:
# İki boyutlu arraydaki 3,9,5 elemanlarına ulaşalım.
array2[1, 1:4]

array([3, 9, 5])

In [31]:
array3

array([[[ 7,  5, 14],
        [21,  8, 11]],

       [[ 8,  6, 20],
        [14,  3,  9]]])

In [32]:
#Üç boyutlu arraydaki 21,8,11 elemanlarına ulaşalım.
array3[0,1,0:]

array([21,  8, 11])

In [33]:
# Üç boyutlu arraydaki 6,20 elemanlarına ulaşalım.
array3[1,0,1:]

array([ 6, 20])

In [34]:
#5 satır 3 sütunluk sıfırlardan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim.
array0 = np.zeros((5,3), dtype = int)
array1 = np.ones ((5,3), dtype = int)

In [35]:
array0

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [36]:
array1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [38]:
#satır bazında birleştir: 
satir = np.concatenate ((array0,array1), axis=0)
satir

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [39]:
#sütun bazında birleştir: 
sutun = np.concatenate ((array0,array1), axis=1)
sutun

array([[0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1]])